In [1]:
import numpy as np
from PIL import Image
import os

In [2]:
data_dir = "/opt/ml/detection/dataset/train"
image_paths = []

In [9]:
profiles = os.listdir(data_dir)
for profile in profiles:
    if profile.startswith("."):  # "." 로 시작하는 파일은 무시합니다
        continue

    image_paths.append(os.path.join(data_dir, profile))
    
print(len(image_paths))

4883


In [10]:
sums = []
squared = []
for image_path in image_paths:
    image = np.array(Image.open(image_path)).astype(np.int32)
    sums.append(image.mean(axis=(0, 1)))
    squared.append((image ** 2).mean(axis=(0, 1)))

mean = np.mean(sums, axis=0) / 255
std = (np.mean(squared, axis=0) - mean ** 2) ** 0.5 / 255

print(mean)
print(std)

[0.48490459 0.46038158 0.43166834]
[0.53942941 0.51570211 0.49422656]


In [11]:
test_data_dir = "/opt/ml/detection/dataset/test"
test_image_paths = []

profiles = os.listdir(test_data_dir)
for profile in profiles:
    test_image_paths.append(os.path.join(test_data_dir, profile))
    
print(len(test_image_paths))

4871


In [12]:
sums = []
squared = []
for image_path in test_image_paths:
    image = np.array(Image.open(image_path)).astype(np.int32)
    sums.append(image.mean(axis=(0, 1)))
    squared.append((image ** 2).mean(axis=(0, 1)))

mean = np.mean(sums, axis=0) / 255
std = (np.mean(squared, axis=0) - mean ** 2) ** 0.5 / 255

print(mean)
print(std)

[0.48342839 0.45935092 0.43051403]
[0.53841915 0.51521523 0.49378081]


In [18]:
train_data_mean = [0.48490459 * 255, 0.46038158 * 255, 0.43166834 * 255]
train_data_std = [0.53942941 * 255, 0.51570211 * 255, 0.49422656 * 255]
print("train_data_mean : ", train_data_mean)
print("train_data_std : ", train_data_std)

train_data_mean :  [123.65067045, 117.3973029, 110.0754267]
train_data_std :  [137.55449955, 131.50403805, 126.0277728]


In [19]:
test_data_mean = [0.48342839 * 255, 0.45935092 * 255, 0.43051403 * 255]
test_data_std = [0.53841915 * 255, 0.51521523 * 255, 0.49378081 * 255]
print("test_data_mean : ", test_data_mean)
print("test_data_std : ", test_data_std)

test_data_mean :  [123.27423945, 117.1344846, 109.78107765]
test_data_std :  [137.29688324999998, 131.37988365, 125.91410655]
